# Generated by Django 6.0.5 on 2026-07-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0006_configuracionnegocio_daily_sales_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('low_stock', 'Low stock'), ('stockout_risk', 'Stockout risk'), ('low_margin', 'Low margin'), ('negative_profit', 'Negative profit'), ('incomplete_recipe', 'Incomplete recipe'), ('missing_cost', 'Missing cost'), ('inactive_customer', 'Inactive customer'), ('sales_growth', 'Sales growth'), ('sales_drop', 'Sales drop'), ('dead_product', 'Dead product'), ('top_product', 'Top product'), ('promotion_expiring', 'Promotion expiring'), ('promotion_performance', 'Promotion performance'), ('pending_orders', 'Pending orders'), ('preparation_delay', 'Preparation delay'), ('business_victory', 'Business victory')], max_length=40)),
                ('category', models.CharField(choices=[('stock', 'Stock'), ('profitability', 'Profitability'), ('sales', 'Sales'), ('customers', 'Customers'), ('promotions', 'Promotions'), ('operations', 'Operations'), ('achievement', 'Achievement')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('score_impact', models.IntegerField(default=0)),
                ('action_label', models.CharField(blank=True, max_length=120)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='negocios.negocio')),
            ],
            options={
                'ordering': ['-priority', 'severity', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'fingerprint'), name='unique_business_opportunity_fingerprint')],
            },
        ),
    ]
