# Generated by Django 6.0.5 on 2026-07-28 01:57

from django.db import migrations, models


def populate_legacy_package_fields(apps, schema_editor):
    PurchaseItem = apps.get_model('purchases', 'PurchaseItem')
    for item in PurchaseItem.objects.all().iterator():
        subtotal = item.subtotal or (item.quantity * item.unit_price)
        item.package_quantity = item.package_quantity or 1
        item.package_type = item.package_type or 'unit'
        item.content_per_package = item.content_per_package or item.quantity
        item.content_unit = item.content_unit or item.unit
        item.total_content_in_stock_unit = item.quantity_in_stock_unit
        item.total_price = subtotal
        item.unit_cost_in_stock_unit = item.new_purchase_price
        item.save(update_fields=[
            'package_quantity',
            'package_type',
            'content_per_package',
            'content_unit',
            'total_content_in_stock_unit',
            'total_price',
            'unit_cost_in_stock_unit',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='content_per_package',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='content_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('unidad', 'unidad'), ('docena', 'docena'), ('caja', 'caja'), ('bolsa', 'bolsa'), ('pack', 'pack')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='package_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='package_type',
            field=models.CharField(choices=[('bag', 'Bag'), ('box', 'Box'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can'), ('sack', 'Sack'), ('unit', 'Unit'), ('other', 'Other')], default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_content_in_stock_unit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_cost_in_stock_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(populate_legacy_package_fields, migrations.RunPython.noop),
    ]
