# Generated by Django 6.0.5 on 2026-07-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('negocios', '0002_negocio_cover_image_negocio_description_and_more'),
        ('productos', '0002_producto_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_price', 'Fixed price')], max_length=20)),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='categorias.categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='negocios.negocio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='productos.producto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
