# Generated by Django 6.0.5 on 2026-07-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventorymovement_pedido_inventorymovement_producto'),
        ('productos', '0002_producto_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('unidad', 'unidad'), ('docena', 'docena'), ('caja', 'caja'), ('bolsa', 'bolsa'), ('pack', 'pack')], max_length=20)),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.ingredient')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='productos.producto')),
            ],
            options={
                'ordering': ['ingredient__name'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'ingredient'), name='unique_recipe_ingredient')],
            },
        ),
    ]
