# Generated by Django 6.0.5 on 2026-07-22 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_pedido_inventorymovement_producto'),
        ('negocios', '0005_configuracionnegocio_cost_increase_alert_percentage_and_more'),
        ('productos', '0002_producto_cost_price'),
        ('recetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_cost_changes', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='inventory.ingredient')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ingredients_count', models.PositiveIntegerField(default=0)),
                ('incomplete_recipe', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('ingredient_cost_change', 'Ingredient cost change'), ('recipe_change', 'Recipe change'), ('product_price_change', 'Product price change')], default='manual', max_length=40)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='productos.producto')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('margin_low', 'Margin low'), ('cost_increase', 'Cost increase'), ('negative_profit', 'Negative profit'), ('incomplete_recipe', 'Incomplete recipe'), ('missing_ingredient_cost', 'Missing ingredient cost')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('read', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_alerts', to='negocios.negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_alerts', to='productos.producto')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved', False)), fields=('negocio', 'producto', 'alert_type'), name='unique_active_profitability_alert')],
            },
        ),
    ]
