# Generated by Django 6.0.5 on 2026-07-21 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0003_configuracionnegocio_businessschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('lacteos', 'Lacteos'), ('carnes', 'Carnes'), ('verduras', 'Verduras'), ('bebidas', 'Bebidas'), ('harinas', 'Harinas'), ('descartables', 'Descartables'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('unidad', 'unidad'), ('docena', 'docena'), ('caja', 'caja'), ('bolsa', 'bolsa'), ('pack', 'pack')], max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='negocios.negocio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('manual_adjustment', 'Manual adjustment'), ('recipe_consumption', 'Recipe consumption'), ('sale_consumption', 'Sale consumption'), ('loss', 'Loss'), ('return', 'Return')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('previous_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('new_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.ingredient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
