# Generated by Django 6.0.5 on 2026-07-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pedidos', '0005_pedido_inventory_restored_at_and_more'),
        ('productos', '0002_producto_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='productos.producto'),
        ),
    ]
