# Generated by Django 6.0.5 on 2026-07-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallepedido_profit_detallepedido_subtotal_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='original_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='promotion_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
