# Generated by Django 6.0.5 on 2026-07-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_delivery_fee_pedido_estimated_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='inventory_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='inventory_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
