# Generated by Django 6.0.5 on 2026-07-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='primary_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
    ]
