# Generated by Django 6.0.5 on 2026-07-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_negocio_cover_image_negocio_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('timezone', models.CharField(default='America/Argentina/Buenos_Aires', max_length=64)),
                ('orders_enabled', models.BooleanField(default=True)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_delivery_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_delivery_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_pickup_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('whatsapp_message_template', models.TextField(blank=True)),
                ('require_customer_phone', models.BooleanField(default=False)),
                ('require_delivery_address', models.BooleanField(default=True)),
                ('show_out_of_stock_products', models.BooleanField(default=True)),
                ('accept_orders_when_closed', models.BooleanField(default=False)),
                ('automatic_order_acceptance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='negocios.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='negocios.negocio')),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'weekday'), name='unique_business_weekday')],
            },
        ),
    ]
