# Generated by Django 6.0.5 on 2026-07-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_configuracionnegocio_businessschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='prevent_sales_without_stock',
            field=models.BooleanField(default=False),
        ),
    ]
