# Generated by Django 6.0.5 on 2026-07-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_configuracionnegocio_prevent_sales_without_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='cost_increase_alert_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='low_margin_threshold',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='target_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=5),
        ),
    ]
