# Generated by Django 6.0.5 on 2026-07-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_configuracionnegocio_cost_increase_alert_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='daily_sales_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='dead_product_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='inactive_customer_days',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='monthly_sales_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
