# Generated by Django 6.0.5 on 2026-07-27 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventorymovement_pedido_inventorymovement_producto'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_text', models.CharField(max_length=255)),
                ('times_confirmed', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_aliases', to='inventory.ingredient')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_aliases', to='purchases.supplier')),
            ],
            options={
                'ordering': ['-times_confirmed', '-last_used_at'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'detected_text', 'supplier'), name='unique_ingredient_alias_per_supplier')],
            },
        ),
    ]
