# Generated by Django 6.0.5 on 2026-07-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientalias',
            name='content_per_package',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredientalias',
            name='content_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ingredientalias',
            name='package_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
